---
slug: davinci_command_line
filename: davinci_command_line
title: DaVinci Coders Building Command Line Skills
subtitle: Learn to become proficient with the terminal
description: This book will help you become proficient with the command line terminal.
author: Jason Noble
copyright: 2016
uuid: 9905d417-4c97-450c-80e3-caf7a224f221
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
